### PR TITLE
fix

### PR DESCRIPTION
**Pull request by SelineSh**

### CODE REVIEW

**Comment by j6villanueva** [comment]
@SelineSh I am going to jump off of this branch so I don't mess w/ your adjustments. Let me know if you need any help

**Comment by shootingdarts** [comment]
@SelineSh Take a look at [this](https://eslint.org/docs/latest/rules/no-case-declarations), it should help.
You can try deleting the eslint.config files to fix the ES linter error.

**Comment by shootingdarts** [comment]
@SelineSh Try deleting eslint.config.js and eslint.config.mjs.

**Comment by SelineSh** [comment]
I think right now there are big problems. Even on the home page to the project page. No matter which page I click on, it jumps straight to the latest page. And nothing on the journal page.

**Review by hakwok — APPROVED** [review]
Perf

**Pull request merged**
