### PR TITLE
E2e testing file creation

### PR DESCRIPTION
**Pull request by j6villanueva**
Creation of the E2E testing file and integration of comments that will be used to build out the tests once the code is done or close to being done.

### CODE REVIEW

**Comment by j6villanueva** [comment]
@shootingdarts do I have to change something in the file to merge?

**Comment by shootingdarts** [comment]
@j6villanueva Take a look at the workflow details, it says you need to change some formatting in the markdown file.

**Comment by j6villanueva** [comment]
Thank you! I will explore it right now.

**Comment by j6villanueva** [comment]
I spent a good couple hours on this. I'm not sure why the lint codebase continues to run, but I'll come back to it later. If you have any guidance, I would really appreciate it.

**Comment by shootingdarts** [comment]
@j6villanueva I am going to close this PR and try another one.

**Pull request closed without merging**
